////
  Copyright 2023 The Bank of New York Mellon.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////

= GraphQL
1.0, March 29, 2022
:toc:

== What is GraphQL?

https://graphql.org/[GraphQL] is a query language and a runtime for APIs.

=== Key Advantages

A few key features that are rarely available to REST API designers which GraphQL supports out of the box are static typing, introspection, extensible data structures, and real-time data.

* Static typing and introspection ensure consistent and predictable results and allow for richer tooling while also making APIs discoverable and transparent.
* The flexible nature of data representation in GraphQL can eliminate overfetching and underfetching and mitigate redundancy.
* Subscriptions provide a mechanism for clients to retrieve data in real-time.

=== Client Server Decoupling

GraphQL allows for greater decoupling between servers and clients than REST APIs are typically able to achieve.

The query language facilitates reusable, flexible, and concise API design. This allows clients to easily build queries to suit their specific needs without relying on communication and support from a backend team to cater to their specific use cases.

The schema works like an API contract. As long as both client and server are in agreement about the schema, they are free to work independently.

The built-in mechanisms for deprecation alleviate the need for complicated versioning with multiple URLs and excessive documentation. They also allow backend developers to iterate on the API with minimal overhead and coordination with downstream clients.

|===
|Next

|link:./type_system.adoc[Type System]
|===
